[package]
name = "qhome"
version = "0.1.0"
authors = ["qwandor"]

[dependencies]
grpc = "0.6"
protobuf = "2"
futures = "0.1"
futures-cpupool = "0.1"
tls-api = "0.1"
tls-api-native-tls = "0.1"
httpbis = "0.7"

[build-dependencies]
protoc-rust-grpc = "0.6"
